name: flutter_bluetooth_basic_example
description: Demonstrates how to use the flutter_bluetooth_basic plugin.
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  path_provider: ^2.1.1
  permission_handler: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_bluetooth_basic:
    path: ../

flutter:
  uses-material-design: true
